AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
